travis:
  secure:
    BINSTAR_TOKEN: MkWvdrt+IjOcHe3buCdSlMI3LOJmFRPWKasi6Z7xbV7DohwIs225ddquB9aGzbxVC1nYNIBaM7RwjwL+PVYeLL4StcJe56eYtZSIXlknYCZzfNKqEoX31F32kgUvxD+XwAXfX3TqO4KwE82elYmKaXrzJNsCLWefyclDz47OpHRD/6HuY1dWaEoAaHqWhlV+/lsT19mUgz8bIMUhE6FAamZY0OOhJ6X7RbggXhxRBpaEMz8Twc3Rs82cBhWZyNWYAY5/gt12ce1fKMvCCZGGr7dN5HclNxPNVHdShHL2+B46XUNmu+CSECkdwlwAPkJE2J9rhqaZDNkSgDb5//GRmYXCeqVr/9c2MmDOR1lY9+Bf1EUBe13fVe+hmhpdj65U7tzuX0maAXUwZeYsShGmnj5TThvFVL0kiHu/GUq/sH0ASp+PR8pAQMW3+MnmNhJXlpcLpGFCEUmfEFAqqYZ9G5jKRxreVY+tGkNAOIYSWxSSvEz/Wu5kozkF/hlBH7Q8tGwImBezG94QyhFTu8+Qxt/ll/wUd/kluCTG/nTpxRO5VMUposu5ai06cXzGGD7bOAERwobX4uxbWH8S6wGjzY37XGK8uqHdnnT87bcO7YLBVqmUZUDu8oyJDVKUA0MGpV+dr510631Cc9d3mI5sx0wVpqXjiO1tpwwGCuJvopM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
